-- +goose Up
-- +goose StatementBegin

-- AUTH
create table auth_permission (
    id       integer generated by default as identity primary key,
    name     varchar(255) not null,
    codename varchar(100) not null unique
);

create index auth_permission_codename
    on auth_permission (codename);

create table auth_user (
    id           integer generated by default as identity primary key,
    password     varchar(128),
    last_login   timestamp with time zone,
    email        varchar(254)             not null unique,
    phone_number varchar(15)                       unique,
    first_name   varchar(150),
    last_name    varchar(150),
    is_active    boolean                  not null default true,
    date_joined  timestamp with time zone not null,
    oauth_id     varchar(255)             unique
);

create index auth_user_oauth_id_like
    on auth_user (oauth_id varchar_pattern_ops);

create index auth_user_email_like
    on auth_user (email varchar_pattern_ops);

create table auth_user_permissions (
    id       bigint generated by default as identity primary key,
    user_id  integer not null
        constraint auth_user_permissions__user_id__fk__auth_user_id
            references auth_user
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_user_permissions__group_id__fk__auth_group_id
            references auth_permission
            deferrable initially deferred,
    constraint auth_user_permissions__user_id_permission_id__unique
        unique (user_id, permission_id)
);

create index auth_user_permissions_user_id
    on auth_user_permissions (user_id);

create index auth_user_permissions_permission_id
    on auth_user_permissions (permission_id);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table auth_permission cascade;
drop table auth_user cascade;
drop table auth_user_permissions cascade;
-- +goose StatementEnd
