-- +goose Up
-- +goose StatementBegin

-- AUTH
create table auth_group
(
    id   integer generated by default as identity primary key,
    name varchar(150) not null unique
);

-- create index auth_group_name_a6ea08ec_like
  --  on auth_group (name varchar_pattern_ops);

create table auth_permission
(
    id       integer generated by default as identity primary key,
    name     varchar(255) not null,
    codename varchar(100) not null unique
);

-- create index auth_permission_content_type_id_2f476e4b
  --  on auth_permission (content_type_id);

create table auth_group_permissions
(
    id            bigint generated by default as identity primary key,
    group_id      integer not null
        constraint auth_group_permissions__group_id__fk__auth_group_id
            references auth_group
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_group_permissio__permission_id__fk__auth_perm
            references auth_permission
            deferrable initially deferred,
    constraint auth_group_permissions__group_id_permission_id__uniq
        unique (group_id, permission_id)
);

-- create index auth_group_permissions_group_id_b120cbf9
  --  on auth_group_permissions (group_id);

-- create index auth_group_permissions_permission_id_84c5c92e
  --  on auth_group_permissions (permission_id);

create table auth_user
(
    id           integer generated by default as identity primary key,
    password     varchar(128),             
    last_login   timestamp with time zone,
    is_superuser boolean                  not null default false,
    email        varchar(254)             not null unique,
    phone_number varchar(15)                       unique,
    first_name   varchar(150),
    last_name    varchar(150),
    is_active    boolean                  not null default true,
    date_joined  timestamp with time zone not null,
    oauth_id     varchar(255)             unique
);

-- create index auth_user_username_6821ab7c_like
  --  on auth_user (username varchar_pattern_ops)

create table auth_user_groups
(
    id       bigint generated by default as identity primary key,
    user_id  integer not null
        constraint auth_user_groups__user_id__fk__auth_user_id
            references auth_user
            deferrable initially deferred,
    group_id integer not null
        constraint auth_user_groups__group_id__fk__auth_group_id
            references auth_group
            deferrable initially deferred,
    constraint auth_user_groups__user_id_group_id__uniq
        unique (user_id, group_id)
);

-- create index auth_user_groups_user_id_6a12ed8b
  --  on auth_user_groups (user_id);

-- create index auth_user_groups_group_id_97559544
  --  on auth_user_groups (group_id);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table auth_group cascade;
drop table auth_permission cascade;
drop table auth_group_permissions cascade;
drop table auth_user cascade;
drop table auth_user_groups cascade;
-- +goose StatementEnd
