//) Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/tikhonp/alcs/internal/db/models/auth"

func AccessPassRequestForm(hosts []auth.User) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"access-pass-request-form\"><h1 class=\"title\">Request an Access Pass</h1><form method=\"POST\" action=\"/user/access-passes/request\" class=\"form\"><!-- Visitor Name --><div class=\"form-group\"><label for=\"visitor_name\">Visitor Name</label> <input type=\"text\" id=\"visitor_name\" name=\"visitor_name\" placeholder=\"Enter visitor&#39;s name\" required></div><!-- Vehicle Number --><div class=\"form-group\"><label for=\"vehicle_number\">Vehicle Number (optional)</label> <input type=\"text\" id=\"vehicle_number\" name=\"vehicle_number\" placeholder=\"Enter vehicle number\"></div><!-- Purpose --><div class=\"form-group\"><label for=\"purpose\">Purpose</label> <textarea id=\"purpose\" name=\"purpose\" placeholder=\"Enter the purpose of your visit\" required></textarea></div><!-- Valid From --><div class=\"form-group\"><label for=\"valid_from\">Valid From</label> <input type=\"date\" id=\"valid_from\" name=\"valid_from\" required></div><!-- Valid Until --><div class=\"form-group\"><label for=\"valid_until\">Valid Until</label> <input type=\"date\" id=\"valid_until\" name=\"valid_until\" required></div><!-- Contact Details --><div class=\"form-group\"><label for=\"contact_details\">Contact Details (optional)</label> <input type=\"text\" id=\"contact_details\" name=\"contact_details\" placeholder=\"Enter contact information\"></div><!-- Host Dropdown --><div class=\"form-group\"><label for=\"host_id\">Host</label> <select id=\"host_id\" name=\"host_id\" required>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, host := range hosts {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(string(host.ID))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/apps/access_pass/views/access_pass_request_form.templ`, Line: 44, Col: 37}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(host.FullName())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/apps/access_pass/views/access_pass_request_form.templ`, Line: 44, Col: 57}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</select></div><!-- Submit Button --><div class=\"form-group\"><button type=\"submit\" class=\"btn btn-primary\">Request Pass</button></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
